### ISSUE TITLE
Error when coming back from a Post view on iOS.

### ISSUE THREAD

**Issue by orballo** [worona/saturn-app-theme-worona#122] opened 2017-09-11 16:35 UTC
It happens only when is first loaded List, and then goes to Post and then back to List. It doesn't throw an error when accessing directly to a Post view and then going back to List.

![screenshot 2017-09-11 18 35 30](https://user-images.githubusercontent.com/13615057/30285930-224d67b0-9720-11e7-9d3b-c87c6941b621.png)

**Comment by Poliuk** [comment] 2017-09-13 15:19
Closing this one for now, we can't reproduce it.

**Closed as completed by Poliuk** 2017-09-13 15:19 UTC
Labels: bug, iOS
